format = "$all($username$hostname )$character"

[character]
success_symbol = '[â¯](bold red)[â¯](bold yellow)[â¯](bold green)'
error_symbol = '[â¯â¯â¯](bold red)'

[hostname]
ssh_only = true
ssh_symbol = "ï„µ "
format = "[$ssh_symbol$hostname]($style)"

[aws]
disabled = true
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"
symbol = "îŒ½  "

[battery]
disabled = true

[buf]
disabled = true
symbol = "ï’ "

[bun]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[c]
disabled = true
format = "\\[[$symbol($version(-$name))]($style)\\]"
symbol = "î˜ "

[cmake]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "\\[[â± $duration]($style)\\]"

[cobol]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[conda]
disabled = true
format = "\\[[$symbol$environment]($style)\\]"
symbol = "ï„Œ "

[crystal]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[daml]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[dart]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜ "

[deno]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " ï ½"
truncate_to_repo = false
truncation_length = 8

[docker_context]
disabled = true
format = "\\[[$symbol$context]($style)\\]"
symbol = "ïŒˆ "

[dotnet]
disabled = true
format = "\\[[$symbol($version)(ğŸ¯ $tfm)]($style)\\]"

[elixir]
disabled = true
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"
symbol = "î‰µ "

[elm]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜¬ "

[erlang]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
disabled = true
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = "ï˜ "

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[golang]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜§ "

[haskell]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î· "

[helm]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
disabled = true
format = "\\[[$symbol$branch]($style)\\]"
symbol = "ï˜ "

[java]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î‰– "

[julia]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜¤ "

[kotlin]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
disabled = true
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[lua]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜  "

[memory_usage]
disabled = true
format = "\\[$symbol[$ram( | $swap)]($style)\\]"
symbol = "ï¡š "

[nim]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "ïš¤ "

[nix_shell]
disabled = false
format = "\\[[$symbol($name)]($style)\\]"
symbol = "ïŒ“ "

[nodejs]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "îœ˜ "

[ocaml]
disabled = true
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[openstack]
disabled = true
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[package]
disabled = true
format = "\\[[$symbol$version]($style)\\]"
symbol = "ï£– "

[perl]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[php]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î˜ˆ "

[pulumi]
disabled = true
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[python]
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"
symbol = "îˆµ "

[raku]
disabled = true
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[rlang]
disabled = true
symbol = "ï³’ "

[ruby]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î‘ "

[rust]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "î¨ "

[scala]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = "îœ· "

[spack]
disabled = true
format = "\\[[$symbol$environment]($style)\\]"
symbol = "ğŸ…¢ "

[sudo]
format = "\\[[as $symbol]\\]"

[swift]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[terraform]
disabled = true
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "[$user]($style) "
show_always = false

[vagrant]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[zig]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
